WIP: SQL Property Graph Queries (SQL/PGQ)
Implementation of SQL property graph queries, according to SQL/PGQ
standard (ISO 9075-16:2023).

Author: Peter Eisentraut <peter@eisentraut.org>
Author: Ashutosh Bapat <ashutosh.bapat.oss@gmail.com>
Discussion: https://www.postgresql.org/message-id/flat/a855795d-e697-4fa5-8698-d20122126567@eisentraut.org

Description of fixes added to the original patch

1. Fixes suggested by pgperltidy.

2. binary_upgrade_set_pg_class_oid() call fix: After
   6e1c4a03a978ed3574124d8f2be22ba2e5a4b1e9
   binary_upgrade_set_pg_class_oid() doesn't need the (now non-existent)
   last argument.

3. decompile_column_index_array() call fix:
   89f908a6d0ac1337c868625008c9598487d184e7 added a new parameter
   withPeriod to decompile_column_index_array(). This function is used
   to decompile keys in property graph definition. KEYs in property
   graph definition are not temporal and thus do not need to specify
   PERIOD in their definition. Hence pass `false` to
   decompile_column_index_array() when called for while decompiling a
   property graph definition.

4. Spurious column not found error: Attribute name from a heap tuple
   needs to be copied before releasing the resources held by the tuple
   and the table scan.

5. Merge conflict fixes in parser.pl: after ECPG related refactoring
   from commits around 6b005499447512abfa1e4add87dcf3e2859c4f9e.

6. Merge conflict in alter.c and aclchk.c when merging with HEAD =
   aac831cafa6f3106dfcbd3298757801c299351fc

7. Fix compilation error in propgraph_element_get_key():
   RelationGetPrimaryKeyIndex(), called by propgraph_element_get_key()
   requires a second argument specifying whether DEFERRED primary key
   constraints are acceptable. SQL/PGQ standard section 9.12, Syntax
   Rule 4 mentions only primary key and does not discuss DEFERREDness.
   Fix compilation failure by passing "true" to
   RelationGetPrimaryKeyIndex() as second argument. No adjustment to the
   documentation is needed since it mentioned primary key without
   DEFERREDness.

8. Merge conflict fixes to gram.y, psql-ref.sgml, psql/help.c,
   primnodes.h when merging with HEAD =
   fd4c4ede708fc5affb04362bb5a8bdc3136fa963

9. Merge conflict fixes to gram.y, describe.c and parallel_schedule when
   merging with HEAD = 75eb9766ec201b62f264554019757716093e2a2f

10. Merge conflict in ExecAlterDefaultPrivilegesStmt() addition of
    Property graph case conflicted with Large objects case when merging
    with HEAD = fd7d7b719137b5c427681a50c0a0ac2d745b68bd. Fix two
    compilation issues introduced as part of this merge. a.  OIDs 8321
    and 8322 conflicted with regdatabase I/O functions respectively.
    Used next unused OIDs.  b.  Fix compilation failure by adding
    RTE_GRAPH_TABLE to switch (rte->rtekind) in
    overexplain_range_table().

Ashutosh Bapat